#!/bin/sh
# Regenerate flam3-3d-hack.patch: the difference between upstream flam3 (the
# commit in release/UPSTREAM) and the patched source in ./flam3, for the
# files in release/MANIFEST.  libtool (generated by configure) and the title
# image (patch cannot carry binary files) are left out.  Needs network access
# to clone upstream.
set -e

TOP=$(cd "$(dirname "$0")" && pwd)
URL=$(sed -n 1p "$TOP/release/UPSTREAM")
COMMIT=$(sed -n 2p "$TOP/release/UPSTREAM")
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

git clone -q "$URL" "$WORK/flam3"
cd "$WORK/flam3"
git checkout -q "$COMMIT"

# Copy the patched upstream files over the clone and let git diff them
grep -v -x -e libtool -e README.md -e test3d.flam3 -e flam3D-title.png \
   "$TOP/release/MANIFEST" > "$WORK/files"
(cd "$TOP/flam3" && tar cf - -T "$WORK/files") | tar xf -

{ git diff
  for f in test3d.flam3 README.md; do
     diff -u /dev/null "$TOP/flam3/$f" | sed "1s|.*|--- /dev/null|;2s|.*|+++ b/$f|" || true
  done
} > "$TOP/flam3-3d-hack.patch"

echo "wrote $TOP/flam3-3d-hack.patch"
